import { Option } from '@mikuroxina/mini-fn';
import type { AccountID } from '../../accounts/model/account.js';
import type { ID } from '../../id/type.js';
import type { NoteID } from '../../notes/model/note.js';
import type { ReactionID } from '../../notes/model/reaction.js';

export type NotificationID = ID<Notification>;
export type NotificationType =
  | 'followed'
  | 'followRequested'
  | 'followAccepted'
  | 'mentioned'
  | 'renoted'
  | 'reacted';

export type NotificationTypeMapValue<Source, Activity> = {
  source: Source;
  activity: Activity;
};

export type NotificationTypeMap = {
  followed: NotificationTypeMapValue<null, null>;
  followRequested: NotificationTypeMapValue<null, null>;
  followAccepted: NotificationTypeMapValue<null, null>;
  mentioned: NotificationTypeMapValue<null, NoteID>;
  renoted: NotificationTypeMapValue<NoteID, NoteID>;
  reacted: NotificationTypeMapValue<NoteID, ReactionID>;
  unknown: NotificationTypeMapValue<never, never>;
};

export type NotificationActorType = 'account' | 'system';

export interface CreateNotificationArgs<T extends NotificationType> {
  /**
   * Notification ID
   */
  id: NotificationID;
  /**
   * Recipient account ID
   */
  recipientID: AccountID;
  /**
   * Notification Type
   * @description
   * - followed: Followed
   * - followRequested: Follow requested
   * - followAccepted: Follow accepted
   * - mentioned: Mentioned
   * - renoted: Renoted
   * - reacted: Reacted
   */
  notificationType: T;
  /**
   *
   */
  sourceID: NotificationTypeMap[T]['source'];
  activityID: NotificationTypeMap[T]['activity'];

  /**
   * Actor(who did the notified action) Type
   * @description
   * - account: Account
   * - system: System
   */
  actorType: NotificationActorType;
  /**
   * Actor account ID
   */
  actorID: AccountID;
  /**
   * Created At
   */
  createdAt: Date;
  /**
   * Read At
   */
  readAt: Option.Option<Date>;
}

export class Notification {
  private readonly id: NotificationID;
  private readonly notificationType: NotificationType;
  private readonly recipientID: AccountID;
  private readonly createdAt: Date;
  private readonly actorType: NotificationActorType;
  private readonly actorID: AccountID;

  private readonly sourceID: NotificationTypeMap[typeof this.notificationType]['source'];
  private readonly activityID: NotificationTypeMap[typeof this.notificationType]['activity'];

  private readAt: Option.Option<Date>;

  private constructor(args: CreateNotificationArgs<NotificationType>) {
    this.id = args.id;
    this.recipientID = args.recipientID;
    this.notificationType = args.notificationType;
    this.actorType = args.actorType;
    this.actorID = args.actorID;
    this.createdAt = args.createdAt;
    this.readAt = args.readAt;

    this.sourceID = args.sourceID;
    this.activityID = args.activityID;
  }

  static new<T extends NotificationType>(
    args: Omit<CreateNotificationArgs<T>, 'isRead' | 'readAt'>,
  ) {
    return new Notification({
      ...args,
      readAt: Option.none(),
    });
  }

  static reconstruct<T extends NotificationType>(
    args: CreateNotificationArgs<T>,
  ) {
    return new Notification(args);
  }

  /**
   * Get Notification ID
   * @example
   * ```
   * "349875930483"
   * ```
   */
  getID(): NotificationID {
    return this.id;
  }

  /**
   * Get recipient account ID
   */
  getRecipientID(): AccountID {
    return this.recipientID;
  }

  /**
   * Get Notification Type
   * @description
   * - followed: Followed
   * - followRequested: Follow requested
   * - followAccepted: Follow accepted
   * - mentioned: Mentioned
   * - renoted: Renoted
   * - reacted: Reacted
   */
  getNotificationType(): NotificationType {
    return this.notificationType;
  }

  /**
   * Get Source ID
   * @description
   * SourceID is the target of the Activity
   *
   * e.g.
   * - notification type is "followed", SourceID is null (Source is Account, but it's already known by recipient)
   * - notification type is "reacted", SourceID is NoteID
   */
  getSourceID(): NotificationTypeMap[typeof this.notificationType]['source'] {
    return this.sourceID;
  }

  /**
   * Get Activity ID
   * @description
   * ActivityID is the object resulting from the operation on Source.
   *
   * e.g.
   * - notification type  "followed", ActivityID is null (no objects are generated when followed)
   * - notification type  "reacted", ActivityID is ReactionID (Reaction is the object generated by the operation)
   */
  getActivityID(): NotificationTypeMap[typeof this.notificationType]['activity'] {
    return this.activityID;
  }

  getCreatedAt(): Date {
    return this.createdAt;
  }

  /**
   * Get Actor(who did the notified action) Type
   * @description
   * - account: Account
   * - system: System
   */
  getActorType(): NotificationActorType {
    return this.actorType;
  }

  /**
   * Get Actor account ID
   */
  getActorID(): AccountID {
    return this.actorID;
  }

  /**
   * Get Read Status
   */
  getIsRead(): boolean {
    return Option.isSome(this.readAt);
  }

  /**
   * Set time when message read
   *
   * NOTE: Once a message has been read, it cannot be marked as unread.
   */
  setRead(date: Date) {
    this.readAt = Option.some(date);
  }

  /**
   * Get date when the notification was read
   */
  getReadAt(): Option.Option<Date> {
    return this.readAt;
  }
}
